apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
spec:
  replicas: 2 # Tell Kubernetes to run 2 copies of our app
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: node-app-container
          image: my-node-app:latest # The name of our Docker image
          ports:
            - containerPort: 3001 # The port our app listens on
          envFrom:
            - secretRef:
                name: mongodb-secret # Pull environment variables from our secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "512m"
            requests:
              memory: "128Mi"
              cpu: "256m"
