apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-role
  namespace: jenkins
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["deployments", "services", "ingresses", "pods"]
    verbs: ["create", "get", "list", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-binding
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-binding-default # A new name for the binding in the default namespace
  namespace: default # Apply this binding in the 'default' namespace
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: jenkins # Grant permissions TO the service account from the 'jenkins' namespace
roleRef:
  kind: Role
  name: jenkins-agent-role # Grant the permissions FROM the role we already created
  apiGroup: rbac.authorization.k8s.io
