name: Node.js CI/CD
on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run lint check
        run: npm run lint
        working-directory: ./app

  build_and_push_to_ecr:
    runs-on: ubuntu-latest
    needs: build_and_test
    outputs:
      image_uri: ${{ steps.set-image-uri.outputs.uri }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v4

      - name: Set Image URI
        id: set-image-uri
        run: |
          ECR_URI_WITHOUT_TAG="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}"
          IMAGE_TAG="${{ github.sha }}"
          echo "uri=${ECR_URI_WITHOUT_TAG}:${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ steps.set-image-uri.outputs.uri }}

  deploy_to_eks:
    runs-on: ubuntu-latest
    needs: build_and_push_to_ecr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig with EKS Cluster details
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes-manifests/
          kubectl set image deployment/my-node-app-deployment node-app-container=${{ needs.build_and_push_to_ecr.outputs.image_uri }}
