name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: my-node-app-repo
  EKS_CLUSTER_NAME: nodejs-eks-project-cluster # Make sure this matches your var.project_name

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} ./app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      - name: Deploy to Amazon EKS
        run: |
          # 1. Update kubeconfig to connect to the cluster
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

          # 2. Authorize GitHub Actions IAM role to manage the cluster
          eksctl create iamidentitymapping \
            --cluster $EKS_CLUSTER_NAME \
            --region $AWS_REGION \
            --arn ${{ secrets.IAM_ROLE_ARN }} \
            --group system:masters \
            --username github-actions-ci

          # 3. Substitute the new image tag in the deployment manifest
          sed -i "s|image:.*|image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|g" kubernetes-manifests/deployment.yaml

          # 4. Apply the updated manifests
          kubectl apply -f kubernetes-manifests/
